# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  config.vm.network :forwarded_port, guest: 22, host: 2224, id: "ssh"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y golang-1.8 python-pip dpkg-dev debhelper dh-systemd
    [ -e /usr/local/bin/go ] || ln -s /usr/lib/go-1.8/bin/go /usr/local/bin/go
  SHELL
end
